version: '3'
services:
    web:
        build: ./
        command: 
            - /bin/sh
            - '-c'
            - /VideoSync/entrypoint.sh
        volumes:
            - ./:/VideoSync/
        ports:
            - 8080:8080
        
        depends_on:
            - broker
            - db

    worker:
        build: ./
        command: "pipenv run celery -A VideoSync worker -l INFO"
        volumes:
            - ./:/VideoSync/
        depends_on:
            - broker
            - db

    schedular:
        build: ./
        command: "pipenv run celery -A VideoSync beat -l INFO"
        volumes:
            - ./:/VideoSync/
        depends_on:
            - broker
            - db

    broker:
        image: redis
        expose:
            - 6379

    db:
        image: postgres
        environment:
            - "POSTGRES_DB=${DATABASE}"
            - "POSTGRES_USER=${USER}"
            - "POSTGRES_PASSWORD=${PASSWORD}"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        expose:
            - 5432