version: '3'
services:
    web:
        build: ./
        command: 
            - /bin/sh 
            - '-c'
            - /VideoSync/entrypoint.sh
        volumes:
            - ./:/VideoSync/
        ports:
            - 8080:8080
        
        depends_on:
            db:
                condition: service_healthy

    worker:
        build: ./
        command: "pipenv run celery -A VideoSync worker -l INFO"
        volumes:
            - ./:/VideoSync/
        depends_on:
            db:
                condition: service_healthy

    schedular:
        build: ./
        command: "pipenv run celery -A VideoSync beat -l INFO"
        volumes:
            - ./:/VideoSync/
        depends_on:
            db:
                condition: service_healthy

    broker:
        image: redis
        expose:
            - 6379

    db:
        image: postgres
        environment:
            - "POSTGRES_DB=${DATABASE}"
            - "POSTGRES_USER=${USER}"
            - "POSTGRES_PASSWORD=${PASSWORD}"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${DATABASE}"]
            interval: 5s
            timeout: 5s
            retries: 5
        expose:
            - 5432