version: '3'
services:
    web:
        build: ./
        command: "pipenv run gunicorn VideoSync.wsgi:application -w 1 --threads 12 --reload --bind 0.0.0.0:8080"
        volumes:
            - ./:/VideoSync/
        ports:
            - 8080:8080
        
        depends_on:
            - broker

    worker:
        build: ./
        command: "pipenv run celery -A VideoSync worker -l INFO"
        volumes:
            - ./:/VideoSync/
        depends_on:
            - broker

    schedular:
        build: ./
        command: "pipenv run celery -A VideoSync beat -l INFO"
        volumes:
            - ./:/VideoSync/
        depends_on:
            - broker

    broker:
        image: redis
        expose:
            - 6379